/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as CompareExperimentsRouteImport } from './routes/compare/experiments'
import { Route as CompareModelsRouteImport } from './routes/compare/models'
import { Route as InspectIndexRouteImport } from './routes/inspect/index'
import { Route as InspectActivationsRouteImport } from './routes/inspect/activations'
import { Route as InspectAttentionRouteImport } from './routes/inspect/attention'
import { Route as InspectEmbeddingsRouteImport } from './routes/inspect/embeddings'
import { Route as InspectGradientsRouteImport } from './routes/inspect/gradients'
import { Route as InspectLossRouteImport } from './routes/inspect/loss'
import { Route as InspectParametersRouteImport } from './routes/inspect/parameters'
import { Route as LabIndexRouteImport } from './routes/lab/index'
import { Route as LabExperimentsRouteImport } from './routes/lab/experiments'
import { Route as LabModelRouteImport } from './routes/lab/model'
import { Route as LabPlaygroundRouteImport } from './routes/lab/playground'
import { Route as LabTokenizerRouteImport } from './routes/lab/tokenizer'
import { Route as LabTrainingRouteImport } from './routes/lab/training'
import { Route as SystemIndexRouteImport } from './routes/system/index'
import { Route as SystemAboutRouteImport } from './routes/system/about'
import { Route as SystemSettingsRouteImport } from './routes/system/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareExperimentsRoute = CompareExperimentsRouteImport.update({
  id: '/compare/experiments',
  path: '/compare/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareModelsRoute = CompareModelsRouteImport.update({
  id: '/compare/models',
  path: '/compare/models',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectIndexRoute = InspectIndexRouteImport.update({
  id: '/inspect/',
  path: '/inspect/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectActivationsRoute = InspectActivationsRouteImport.update({
  id: '/inspect/activations',
  path: '/inspect/activations',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectAttentionRoute = InspectAttentionRouteImport.update({
  id: '/inspect/attention',
  path: '/inspect/attention',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectEmbeddingsRoute = InspectEmbeddingsRouteImport.update({
  id: '/inspect/embeddings',
  path: '/inspect/embeddings',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectGradientsRoute = InspectGradientsRouteImport.update({
  id: '/inspect/gradients',
  path: '/inspect/gradients',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectLossRoute = InspectLossRouteImport.update({
  id: '/inspect/loss',
  path: '/inspect/loss',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectParametersRoute = InspectParametersRouteImport.update({
  id: '/inspect/parameters',
  path: '/inspect/parameters',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabExperimentsRoute = LabExperimentsRouteImport.update({
  id: '/lab/experiments',
  path: '/lab/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const LabModelRoute = LabModelRouteImport.update({
  id: '/lab/model',
  path: '/lab/model',
  getParentRoute: () => rootRouteImport,
} as any)
const LabPlaygroundRoute = LabPlaygroundRouteImport.update({
  id: '/lab/playground',
  path: '/lab/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LabTokenizerRoute = LabTokenizerRouteImport.update({
  id: '/lab/tokenizer',
  path: '/lab/tokenizer',
  getParentRoute: () => rootRouteImport,
} as any)
const LabTrainingRoute = LabTrainingRouteImport.update({
  id: '/lab/training',
  path: '/lab/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIndexRoute = SystemIndexRouteImport.update({
  id: '/system/',
  path: '/system/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemAboutRoute = SystemAboutRouteImport.update({
  id: '/system/about',
  path: '/system/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSettingsRoute = SystemSettingsRouteImport.update({
  id: '/system/settings',
  path: '/system/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare/experiments': typeof CompareExperimentsRoute
  '/compare/models': typeof CompareModelsRoute
  '/inspect/activations': typeof InspectActivationsRoute
  '/inspect/attention': typeof InspectAttentionRoute
  '/inspect/embeddings': typeof InspectEmbeddingsRoute
  '/inspect/gradients': typeof InspectGradientsRoute
  '/inspect/loss': typeof InspectLossRoute
  '/inspect/parameters': typeof InspectParametersRoute
  '/lab/experiments': typeof LabExperimentsRoute
  '/lab/model': typeof LabModelRoute
  '/lab/playground': typeof LabPlaygroundRoute
  '/lab/tokenizer': typeof LabTokenizerRoute
  '/lab/training': typeof LabTrainingRoute
  '/system/about': typeof SystemAboutRoute
  '/system/settings': typeof SystemSettingsRoute
  '/compare/': typeof CompareIndexRoute
  '/inspect/': typeof InspectIndexRoute
  '/lab/': typeof LabIndexRoute
  '/system/': typeof SystemIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare/experiments': typeof CompareExperimentsRoute
  '/compare/models': typeof CompareModelsRoute
  '/inspect/activations': typeof InspectActivationsRoute
  '/inspect/attention': typeof InspectAttentionRoute
  '/inspect/embeddings': typeof InspectEmbeddingsRoute
  '/inspect/gradients': typeof InspectGradientsRoute
  '/inspect/loss': typeof InspectLossRoute
  '/inspect/parameters': typeof InspectParametersRoute
  '/lab/experiments': typeof LabExperimentsRoute
  '/lab/model': typeof LabModelRoute
  '/lab/playground': typeof LabPlaygroundRoute
  '/lab/tokenizer': typeof LabTokenizerRoute
  '/lab/training': typeof LabTrainingRoute
  '/system/about': typeof SystemAboutRoute
  '/system/settings': typeof SystemSettingsRoute
  '/compare': typeof CompareIndexRoute
  '/inspect': typeof InspectIndexRoute
  '/lab': typeof LabIndexRoute
  '/system': typeof SystemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare/experiments': typeof CompareExperimentsRoute
  '/compare/models': typeof CompareModelsRoute
  '/inspect/activations': typeof InspectActivationsRoute
  '/inspect/attention': typeof InspectAttentionRoute
  '/inspect/embeddings': typeof InspectEmbeddingsRoute
  '/inspect/gradients': typeof InspectGradientsRoute
  '/inspect/loss': typeof InspectLossRoute
  '/inspect/parameters': typeof InspectParametersRoute
  '/lab/experiments': typeof LabExperimentsRoute
  '/lab/model': typeof LabModelRoute
  '/lab/playground': typeof LabPlaygroundRoute
  '/lab/tokenizer': typeof LabTokenizerRoute
  '/lab/training': typeof LabTrainingRoute
  '/system/about': typeof SystemAboutRoute
  '/system/settings': typeof SystemSettingsRoute
  '/compare/': typeof CompareIndexRoute
  '/inspect/': typeof InspectIndexRoute
  '/lab/': typeof LabIndexRoute
  '/system/': typeof SystemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare/experiments'
    | '/compare/models'
    | '/inspect/activations'
    | '/inspect/attention'
    | '/inspect/embeddings'
    | '/inspect/gradients'
    | '/inspect/loss'
    | '/inspect/parameters'
    | '/lab/experiments'
    | '/lab/model'
    | '/lab/playground'
    | '/lab/tokenizer'
    | '/lab/training'
    | '/system/about'
    | '/system/settings'
    | '/compare/'
    | '/inspect/'
    | '/lab/'
    | '/system/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare/experiments'
    | '/compare/models'
    | '/inspect/activations'
    | '/inspect/attention'
    | '/inspect/embeddings'
    | '/inspect/gradients'
    | '/inspect/loss'
    | '/inspect/parameters'
    | '/lab/experiments'
    | '/lab/model'
    | '/lab/playground'
    | '/lab/tokenizer'
    | '/lab/training'
    | '/system/about'
    | '/system/settings'
    | '/compare'
    | '/inspect'
    | '/lab'
    | '/system'
  id:
    | '__root__'
    | '/'
    | '/compare/experiments'
    | '/compare/models'
    | '/inspect/activations'
    | '/inspect/attention'
    | '/inspect/embeddings'
    | '/inspect/gradients'
    | '/inspect/loss'
    | '/inspect/parameters'
    | '/lab/experiments'
    | '/lab/model'
    | '/lab/playground'
    | '/lab/tokenizer'
    | '/lab/training'
    | '/system/about'
    | '/system/settings'
    | '/compare/'
    | '/inspect/'
    | '/lab/'
    | '/system/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareExperimentsRoute: typeof CompareExperimentsRoute
  CompareModelsRoute: typeof CompareModelsRoute
  InspectActivationsRoute: typeof InspectActivationsRoute
  InspectAttentionRoute: typeof InspectAttentionRoute
  InspectEmbeddingsRoute: typeof InspectEmbeddingsRoute
  InspectGradientsRoute: typeof InspectGradientsRoute
  InspectLossRoute: typeof InspectLossRoute
  InspectParametersRoute: typeof InspectParametersRoute
  LabExperimentsRoute: typeof LabExperimentsRoute
  LabModelRoute: typeof LabModelRoute
  LabPlaygroundRoute: typeof LabPlaygroundRoute
  LabTokenizerRoute: typeof LabTokenizerRoute
  LabTrainingRoute: typeof LabTrainingRoute
  SystemAboutRoute: typeof SystemAboutRoute
  SystemSettingsRoute: typeof SystemSettingsRoute
  CompareIndexRoute: typeof CompareIndexRoute
  InspectIndexRoute: typeof InspectIndexRoute
  LabIndexRoute: typeof LabIndexRoute
  SystemIndexRoute: typeof SystemIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/experiments': {
      id: '/compare/experiments'
      path: '/compare/experiments'
      fullPath: '/compare/experiments'
      preLoaderRoute: typeof CompareExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/models': {
      id: '/compare/models'
      path: '/compare/models'
      fullPath: '/compare/models'
      preLoaderRoute: typeof CompareModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/': {
      id: '/inspect/'
      path: '/inspect'
      fullPath: '/inspect/'
      preLoaderRoute: typeof InspectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/activations': {
      id: '/inspect/activations'
      path: '/inspect/activations'
      fullPath: '/inspect/activations'
      preLoaderRoute: typeof InspectActivationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/attention': {
      id: '/inspect/attention'
      path: '/inspect/attention'
      fullPath: '/inspect/attention'
      preLoaderRoute: typeof InspectAttentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/embeddings': {
      id: '/inspect/embeddings'
      path: '/inspect/embeddings'
      fullPath: '/inspect/embeddings'
      preLoaderRoute: typeof InspectEmbeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/gradients': {
      id: '/inspect/gradients'
      path: '/inspect/gradients'
      fullPath: '/inspect/gradients'
      preLoaderRoute: typeof InspectGradientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/loss': {
      id: '/inspect/loss'
      path: '/inspect/loss'
      fullPath: '/inspect/loss'
      preLoaderRoute: typeof InspectLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/parameters': {
      id: '/inspect/parameters'
      path: '/inspect/parameters'
      fullPath: '/inspect/parameters'
      preLoaderRoute: typeof InspectParametersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/experiments': {
      id: '/lab/experiments'
      path: '/lab/experiments'
      fullPath: '/lab/experiments'
      preLoaderRoute: typeof LabExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/model': {
      id: '/lab/model'
      path: '/lab/model'
      fullPath: '/lab/model'
      preLoaderRoute: typeof LabModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/playground': {
      id: '/lab/playground'
      path: '/lab/playground'
      fullPath: '/lab/playground'
      preLoaderRoute: typeof LabPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/tokenizer': {
      id: '/lab/tokenizer'
      path: '/lab/tokenizer'
      fullPath: '/lab/tokenizer'
      preLoaderRoute: typeof LabTokenizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/training': {
      id: '/lab/training'
      path: '/lab/training'
      fullPath: '/lab/training'
      preLoaderRoute: typeof LabTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/': {
      id: '/system/'
      path: '/system'
      fullPath: '/system/'
      preLoaderRoute: typeof SystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/about': {
      id: '/system/about'
      path: '/system/about'
      fullPath: '/system/about'
      preLoaderRoute: typeof SystemAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/settings': {
      id: '/system/settings'
      path: '/system/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof SystemSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareExperimentsRoute: CompareExperimentsRoute,
  CompareModelsRoute: CompareModelsRoute,
  InspectActivationsRoute: InspectActivationsRoute,
  InspectAttentionRoute: InspectAttentionRoute,
  InspectEmbeddingsRoute: InspectEmbeddingsRoute,
  InspectGradientsRoute: InspectGradientsRoute,
  InspectLossRoute: InspectLossRoute,
  InspectParametersRoute: InspectParametersRoute,
  LabExperimentsRoute: LabExperimentsRoute,
  LabModelRoute: LabModelRoute,
  LabPlaygroundRoute: LabPlaygroundRoute,
  LabTokenizerRoute: LabTokenizerRoute,
  LabTrainingRoute: LabTrainingRoute,
  SystemAboutRoute: SystemAboutRoute,
  SystemSettingsRoute: SystemSettingsRoute,
  CompareIndexRoute: CompareIndexRoute,
  InspectIndexRoute: InspectIndexRoute,
  LabIndexRoute: LabIndexRoute,
  SystemIndexRoute: SystemIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
